Fix modules build
In file included from /Users/alex/cheri/llvm-project/llvm/lib/Target/RISCV/RISCVISelLowering.cpp:39:
In file included from /Users/alex/cheri/llvm-project/llvm/lib/Target/RISCV/cheri-compressed-cap/cheri_compressed_cap.h:42:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdbool.h:29:1: fatal error: import of module 'Darwin.C.stdbool' appears within namespace '(anonymous)'
#include_next <stdbool.h>
^
/Users/alex/cheri/llvm-project/llvm/lib/Target/RISCV/RISCVISelLowering.cpp:38:1: note: namespace '(anonymous)' begins here
namespace {
^

All functions in cheri_compressed_cap.h should be static inline so this
should not make any difference.